# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mika/Documents/snowglobe/deps/sexp-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mika/Documents/snowglobe/deps/sexp-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mika/Documents/snowglobe/deps/sexp-cpp/CMakeFiles /home/mika/Documents/snowglobe/deps/sexp-cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mika/Documents/snowglobe/deps/sexp-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sexp

# Build rule for target.
sexp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sexp
.PHONY : sexp

# fast build rule for target.
sexp/fast:
	$(MAKE) -f CMakeFiles/sexp.dir/build.make CMakeFiles/sexp.dir/build
.PHONY : sexp/fast

src/io.o: src/io.cpp.o

.PHONY : src/io.o

# target to build an object file
src/io.cpp.o:
	$(MAKE) -f CMakeFiles/sexp.dir/build.make CMakeFiles/sexp.dir/src/io.cpp.o
.PHONY : src/io.cpp.o

src/io.i: src/io.cpp.i

.PHONY : src/io.i

# target to preprocess a source file
src/io.cpp.i:
	$(MAKE) -f CMakeFiles/sexp.dir/build.make CMakeFiles/sexp.dir/src/io.cpp.i
.PHONY : src/io.cpp.i

src/io.s: src/io.cpp.s

.PHONY : src/io.s

# target to generate assembly for a file
src/io.cpp.s:
	$(MAKE) -f CMakeFiles/sexp.dir/build.make CMakeFiles/sexp.dir/src/io.cpp.s
.PHONY : src/io.cpp.s

src/lexer.o: src/lexer.cpp.o

.PHONY : src/lexer.o

# target to build an object file
src/lexer.cpp.o:
	$(MAKE) -f CMakeFiles/sexp.dir/build.make CMakeFiles/sexp.dir/src/lexer.cpp.o
.PHONY : src/lexer.cpp.o

src/lexer.i: src/lexer.cpp.i

.PHONY : src/lexer.i

# target to preprocess a source file
src/lexer.cpp.i:
	$(MAKE) -f CMakeFiles/sexp.dir/build.make CMakeFiles/sexp.dir/src/lexer.cpp.i
.PHONY : src/lexer.cpp.i

src/lexer.s: src/lexer.cpp.s

.PHONY : src/lexer.s

# target to generate assembly for a file
src/lexer.cpp.s:
	$(MAKE) -f CMakeFiles/sexp.dir/build.make CMakeFiles/sexp.dir/src/lexer.cpp.s
.PHONY : src/lexer.cpp.s

src/parser.o: src/parser.cpp.o

.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) -f CMakeFiles/sexp.dir/build.make CMakeFiles/sexp.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i

.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) -f CMakeFiles/sexp.dir/build.make CMakeFiles/sexp.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s

.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) -f CMakeFiles/sexp.dir/build.make CMakeFiles/sexp.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/util.o: src/util.cpp.o

.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) -f CMakeFiles/sexp.dir/build.make CMakeFiles/sexp.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) -f CMakeFiles/sexp.dir/build.make CMakeFiles/sexp.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) -f CMakeFiles/sexp.dir/build.make CMakeFiles/sexp.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

src/value.o: src/value.cpp.o

.PHONY : src/value.o

# target to build an object file
src/value.cpp.o:
	$(MAKE) -f CMakeFiles/sexp.dir/build.make CMakeFiles/sexp.dir/src/value.cpp.o
.PHONY : src/value.cpp.o

src/value.i: src/value.cpp.i

.PHONY : src/value.i

# target to preprocess a source file
src/value.cpp.i:
	$(MAKE) -f CMakeFiles/sexp.dir/build.make CMakeFiles/sexp.dir/src/value.cpp.i
.PHONY : src/value.cpp.i

src/value.s: src/value.cpp.s

.PHONY : src/value.s

# target to generate assembly for a file
src/value.cpp.s:
	$(MAKE) -f CMakeFiles/sexp.dir/build.make CMakeFiles/sexp.dir/src/value.cpp.s
.PHONY : src/value.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sexp"
	@echo "... src/io.o"
	@echo "... src/io.i"
	@echo "... src/io.s"
	@echo "... src/lexer.o"
	@echo "... src/lexer.i"
	@echo "... src/lexer.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... src/value.o"
	@echo "... src/value.i"
	@echo "... src/value.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

